# -*- coding: utf-8 -*-
"""PRODIGY_CS_03.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Fbb_oxgbvpmmYU3Y0ow9Wlmy_Tq23BFZ
"""

import re

def assess_password_strength(password):
    # Criteria checks
    criteria = [
        (len(password) >= 8, "Password should be at least 8 characters long."),
        (re.search(r'[A-Z]', password), "Include at least one uppercase letter."),
        (re.search(r'[a-z]', password), "Include at least one lowercase letter."),
        (re.search(r'[0-9]', password), "Include at least one number."),
        (re.search(r'[!@#$%^&*(),.?":{}|<>]', password), "Include at least one special character."),
    ]

    score = sum(1 for check, _ in criteria if check)
    strength = ["Weak", "rerate", "Strong"][min(score // 2, 2)]

    feedback = [msg for check, msg in criteria if not check]

    return strength, feedback

password = input("Enter your password: ")
strength, feedback = assess_password_strength(password)

print(f"Password Strength: {strength}")
for item in feedback:
    print(f"- {item}")